name: Java Checkstyle

on:
  pull_request

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # puedes usar otra JDK si quieres
          java-version: '17'        # versión de Java que uses

      - name: Build project with Maven
        run: mvn compile

      - name: Run Checkstyle
        run: cd RECUPERACION_AGILES_ISMAEL/AGILES_RECU && mvn checkstyle:check
